from dataclasses import asdict, dataclass
from datetime import datetime
from ipaddress import ip_address
from typing import Any


ALLOWED_VM_NAMES = {
    "VM1",
    "VM2",
    "VM3",
}


@dataclass(frozen=True)
class SecurityLog:
    """
    Represents one security log generated by a VM or server.
    """

    log_id: str
    timestamp: str
    vm_name: str
    event_type: str
    source_ip: str
    destination_ip: str
    message: str
    username: str | None = None
    attempt_count: int | None = None

    @classmethod
    def from_dict(cls, log_data: dict[str, Any]) -> "SecurityLog":
        """
        Validate a dictionary and convert it into a SecurityLog object.
        """

        if not isinstance(log_data, dict):
            raise ValueError("Security log must be a dictionary.")

        log_id = cls._read_required_text(
            log_data,
            "log_id",
        )

        timestamp = cls._read_required_text(
            log_data,
            "timestamp",
        )

        vm_name = cls._read_required_text(
            log_data,
            "vm_name",
        )

        event_type = cls._read_required_text(
            log_data,
            "event_type",
        )

        source_ip = cls._read_required_text(
            log_data,
            "source_ip",
        )

        destination_ip = cls._read_required_text(
            log_data,
            "destination_ip",
        )

        message = cls._read_required_text(
            log_data,
            "message",
        )

        cls._validate_timestamp(timestamp)
        cls._validate_ip_address(source_ip, "source_ip")
        cls._validate_ip_address(destination_ip, "destination_ip")

        if vm_name not in ALLOWED_VM_NAMES:
            raise ValueError(
                f"Invalid vm_name '{vm_name}'. "
                f"Allowed values: {sorted(ALLOWED_VM_NAMES)}"
            )

        username = log_data.get("username")

        if username is not None:
            if not isinstance(username, str):
                raise ValueError("username must be a string.")

            username = username.strip()

            if not username:
                username = None

        attempt_count = log_data.get("attempt_count")

        if attempt_count is not None:
            if isinstance(attempt_count, bool) or not isinstance(
                attempt_count,
                int,
            ):
                raise ValueError("attempt_count must be an integer.")

            if attempt_count < 0:
                raise ValueError(
                    "attempt_count cannot be negative."
                )

        return cls(
            log_id=log_id,
            timestamp=timestamp,
            vm_name=vm_name,
            event_type=event_type,
            source_ip=source_ip,
            destination_ip=destination_ip,
            message=message,
            username=username,
            attempt_count=attempt_count,
        )

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the SecurityLog object back into a dictionary.
        """

        log_data = asdict(self)

        return {
            field_name: field_value
            for field_name, field_value in log_data.items()
            if field_value is not None
        }

    @staticmethod
    def _read_required_text(
        log_data: dict[str, Any],
        field_name: str,
    ) -> str:
        """
        Read and validate one required text field.
        """

        field_value = log_data.get(field_name)

        if not isinstance(field_value, str):
            raise ValueError(
                f"{field_name} must be a string."
            )

        cleaned_value = field_value.strip()

        if not cleaned_value:
            raise ValueError(
                f"{field_name} is required and cannot be empty."
            )

        return cleaned_value

    @staticmethod
    def _validate_timestamp(timestamp: str) -> None:
        """
        Confirm that the timestamp uses ISO 8601 format.
        """

        normalized_timestamp = timestamp.replace(
            "Z",
            "+00:00",
        )

        try:
            datetime.fromisoformat(normalized_timestamp)
        except ValueError as error:
            raise ValueError(
                "timestamp must use ISO 8601 format. "
                "Example: 2026-07-11T20:30:00"
            ) from error

    @staticmethod
    def _validate_ip_address(
        ip_value: str,
        field_name: str,
    ) -> None:
        """
        Confirm that the value is a valid IPv4 or IPv6 address.
        """

        try:
            ip_address(ip_value)
        except ValueError as error:
            raise ValueError(
                f"{field_name} must be a valid IP address."
            ) from error