// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFx37ortnkpWKtKGpdKkkXoBgAek6aww',
    appId: '1:804056850566:web:74167853ed88bafae17107',
    messagingSenderId: '804056850566',
    projectId: 'bluealert-cee60',
    authDomain: 'bluealert-cee60.firebaseapp.com',
    databaseURL:
        'https://bluealert-cee60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluealert-cee60.firebasestorage.app',
    measurementId: 'G-YKSHZ21D7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHH2Pxbp6daJU5CcHfIVkWgxVHK94p-4',
    appId: '1:804056850566:android:e4dfc140cddeb947e17107',
    messagingSenderId: '804056850566',
    projectId: 'bluealert-cee60',
    databaseURL:
        'https://bluealert-cee60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluealert-cee60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNaXfUdGLomWmRAJsOwY5PQuDs8E9FEZY',
    appId: '1:804056850566:ios:02c10f52abfc61a1e17107',
    messagingSenderId: '804056850566',
    projectId: 'bluealert-cee60',
    databaseURL:
        'https://bluealert-cee60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluealert-cee60.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNaXfUdGLomWmRAJsOwY5PQuDs8E9FEZY',
    appId: '1:804056850566:ios:02c10f52abfc61a1e17107',
    messagingSenderId: '804056850566',
    projectId: 'bluealert-cee60',
    databaseURL:
        'https://bluealert-cee60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluealert-cee60.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFx37ortnkpWKtKGpdKkkXoBgAek6aww',
    appId: '1:804056850566:web:485124a111fcc793e17107',
    messagingSenderId: '804056850566',
    projectId: 'bluealert-cee60',
    authDomain: 'bluealert-cee60.firebaseapp.com',
    databaseURL:
        'https://bluealert-cee60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluealert-cee60.firebasestorage.app',
    measurementId: 'G-R4JDPN2MQB',
  );
}
